experimentName = 'batch-18';

%
% Batch
%

config.batch.filenames = {...
    'stones.PNG',...    
    'eggs.PNG',...    
    'flowers.PNG',...    
    'Cantera1.PNG',...
    'Cantera2.PNG',...
    'Scagliola.PNG',...
    'birds.PNG',...
    'brick.PNG',...
    'droplets.PNG',...
    'fabric.PNG',...
    'fossil.PNG',...
    'lava.PNG',...
    'moss.PNG',...
    'olives.PNG',...
    'paintpeel.PNG',...
    'rustspots.PNG',...
    'stone.PNG',...
    'wetsand.PNG'};

% config.batch.filenames = {...
%     'NCcloud1.jpg',...
%     'NWood_Lite_4.jpg',...
%     'Nmossybark.jpg',...
%     'Nmoutain1.jpg',...
%     'S3001.jpg',...
%     'SBflake.jpg',...
%     'Shexpave2.jpg',...
%     'windows.jpg'};

% config.batch.filenames = {...
%     'eggs.PNG',...
%     'flowers.PNG',...
%     'stones.PNG'};


config.batch.filenames = {...
    'stones.PNG',...    
    'eggs.PNG',...    
    'birds.PNG',...
    'droplets.PNG',...
    'fabric.PNG',...
    'olives.PNG',...
    'rustspots.PNG'};

config.batch.synth_scale = [2 2];

%
% Textonizer
%
config.textonizer.method = 'standard';

config.textonizer.visual.texton_clusters = 5;
config.textonizer.visual.fb.orientations = pi/6;
config.textonizer.visual.fb.scales = 4;
config.textonizer.visual.filter_dim = 6;
config.textonizer.visual.color_features = 'rgb';
config.textonizer.visual.final_pca = false;

config.textonizer.semantic.method = 'eran';
config.textonizer.semantic.texton_per_class = 5;
config.textonizer.semantic.texton_clusters = 3;
config.textonizer.semantic.texton_amount_method = 'threshold';
config.textonizer.semantic.min_texton_area = 25;
config.textonizer.semantic.fill_holes = false;

%
% Synthesizer
%
config.synthesizer.newSize = [];
config.synthesizer.method = 'map';
config.synthesizer.map.method = 'quilt';
config.synthesizer.map.quilt.dist.method = 'tile';
config.synthesizer.map.quilt.weights.spatial = 1;
config.synthesizer.map.quilt.weights.frequency = 0.5;

config.synthesizer.scales = [0.75,1];
config.synthesizer.candidates_max = 2;

config.synthesizer.weights.area = 0.3;
config.synthesizer.weights.texton = 0.4;
config.synthesizer.weights.crude = 0.25;
config.synthesizer.weights.ref = 1;
                
save(fullfile(getConst('EXP_CONFIG_PATH'), experimentName), 'config');


%config.textonizer.gradient.max_iter = 1000;
%config.textonizer.gradient.eta = 1e-8;
%config.textonizer.gradient.weights.volume = -1e6;

%config.textonizer.semantic.scales_amount = 10;
%config.textonizer.semantic.window_sizes = [40 40];
%config.textonizer.semantic.window_overlap = [0.5 0.5];